name: Release VS Code Extension

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  packages: write

jobs:
  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install vsce
        run: npm install -g @vscode/vsce

      - name: Install dependencies
        run: npm install

      - name: Rebuild @nut-tree-fork/nut-js for macOS
        run: npm rebuild @nut-tree-fork/nut-js || true

      - name: Package VSIX for macOS
        run: vsce package --out code-viewer-bot-macos.vsix

      - name: Upload macOS Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: 'code-viewer-bot-macos.vsix'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install vsce
        run: npm install -g @vscode/vsce

      - name: Install dependencies
        run: npm install

      - name: Rebuild @nut-tree-fork/nut-js for Windows
        run: npm rebuild @nut-tree-fork/nut-js || true

      - name: Package VSIX for Windows
        run: vsce package --out code-viewer-bot-windows.vsix

      - name: Upload Windows Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: 'code-viewer-bot-windows.vsix'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
