name: Release VS Code Extension

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  packages: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: darwin-arm64
            asset_name: code-viewer-bot-darwin-arm64.vsix
          - os: macos-15-intel
            target: darwin-x64
            asset_name: code-viewer-bot-darwin-x64.vsix
          - os: windows-latest
            target: win32-x64
            asset_name: code-viewer-bot-win32-x64.vsix

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Set up Node.js 24
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - name: Install @vscode/vsce
        run: npm install -g @vscode/vsce

      - name: Install dependencies
        run: npm ci

      - name: Build extension bundle
        run: npm run build

      - name: Rebuild robotjs
        run: npm rebuild robotjs || true

      - name: Package VSIX
        run: vsce package --target ${{ matrix.target }} --out ${{ matrix.asset_name }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2.5.0
        with:
          files: ${{ matrix.asset_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
